### ISSUE TITLE
初来乍到, 一些拙见

### ISSUE THREAD

**Issue by nobodxbodon** [the-language/the-language-archive#1]
1. 有没有相应的测试用例? 在readme中的说明对于不了解lisp/scheme的编程新手来说估计非常陌生. 在补充文档之前, 每个功能有至少一个测试用例的话, 至少有个参考. 
2. 关于文档, 在http://语.ml/ 中的例子基础上, 最好再加些说明, 比如`甲 : 物？`是什么意思. 因为scheme非常小众, 恐怕知道letrec的开发者比例很小. 另外, 个人对scheme略有了解, 但看到这个说明时仍然不大明白. 也许用scheme中的对应语句可以更清楚说明语义? :
```

(首尾？ 甲) → 陰陽？
--
甲 : 物？

返回甲是否是(首尾 之首 之尾)。 
```

3. 语言的关键词选取上, 现在似乎采取简约的缩写为多. 之前在这个帖子里有一些相关讨论: https://github.com/program-in-chinese/overview/issues/40 个人认为可读性也需考虑, 欢迎一同探讨.
4. 可否考虑在源码中使用中文命名? 毕竟参与者都会中文, 而代码可读性也会更好. 比如在下的一个实验语言(刚开头)的[代码片段](https://github.com/program-in-chinese/quan5/blob/master/src/main/java/com/%E4%B8%AD%E6%96%87%E7%BC%96%E7%A8%8B/%E5%9C%885/%E5%88%86%E6%9E%90%E5%99%A8/%E5%AE%9A%E5%88%B6%E8%AE%BF%E9%97%AE%E5%99%A8.java)

**Comment by zaoqi** [comment]
這只是核心，不是直接用來solve problems · make languages的。初學者不需要會。
我會編寫一個用來solve problems · make languages的庫。

**Comment by zaoqi** [comment]
`:`是指類型 Racket要求寫

**Comment by zaoqi** [comment]
這是核心，將很少會有人讀

**Comment by zaoqi** [comment]
我認爲現在可讀性很好

**Comment by zaoqi** [comment]
现在的Haskell实现是临时的，不符合标准的： 不支持无限循环数据
我准备写一个编译器，没想好编译到Clojure还是Lua还是Ocaml
