### ISSUE TITLE
命名

### ISSUE THREAD

**Issue by zaoqi** [the-language/the-language-archive#2]
这里用伪代码表示命名
现在命名中名词在前面，所以有(a -> b)类似自然语言的表示
如果像Lisp语法一样把动词放在前面
+ (? (数 自然))
+ (-> (列 字) (数 自然))
自然数怎么命名？
+ (自然 数)
+ (数 自然)
+ (quote (自然 数))
+ (quote (数 自然))
+ (子 数 自然)
+ ...

**Comment by zaoqi** [comment]
@nobodxbodon @xieyuheng

**Comment by nobodxbodon** [comment]
语义是定义一个自然数还是判断一个量的类型?
如果是后者, 为何拆开写而不这样？
```
（自然数? 12）
```
另外, 是否也要定义`整数`,或者更广泛的`数`?

**Comment by zaoqi** [comment]
自然数是一个数
我没有用大部分Lisp的symbol

**Comment by zaoqi** [comment]
@nobodxbodon 似乎用(? (数 自然)) (-> (列 字) (数 自然)) 有点问题

**Comment by nobodxbodon** [comment]
`(? (数 自然)) (-> (列 字) (数 自然))` 抱歉看不懂
具体解释一下语义?
我不会Haskell/ocaml/coq

**Comment by zaoqi** [comment]
@nobodxbodon 
這是仿scheme/racket的語法
->表示轉換
?本來寫在最後

**Comment by zaoqi** [comment]
@nobodxbodon
我用S-Exp更精确的表示symbol

**Comment by nobodxbodon** [comment]
scheme里:
```
> (set! a 10)
> (number? a)
#t
```
请问你这里想实现的是哪部分?

**Comment by zaoqi** [comment]
我用S-Exp表示number?等
现在表示为
(number ?)

**Comment by zaoqi** [comment]
表示为
(? number)可能更好

**Comment by nobodxbodon** [comment]
如果拆开`自然`和`数`, 一般开发者可能会不习惯, 毕竟这个概念从小就有了. 另外, 与之配套的还要`数 小`吗?

**Comment by zaoqi** [comment]
语法中可以用 自然-数 或 数-自然 表示

**Comment by nobodxbodon** [comment]
根据https://www.wikihow.com/Create-a-Programming-Language , 在具体的语法定义(第七步)之前, 请问有没有解决具体问题的例程?
> 5 Think of some specific tasks that someone would want to be able to perform with your language. For example, 'they may want to direct a robot to follow a line' or 'they may want to create relatively portable desktop programs in it' or 'they may want to create web applications with it'.

> 6 Experiment with syntax ideas (the text of the language) for the above examples.

> 7 Write out a formal grammar for the syntax.

**Comment by nobodxbodon** [comment]
比如另一个开发工具的例程: https://github.com/HL4A/hl4a.cyzy/blob/master/%E6%BA%90%E7%A0%81/%E5%85%A5%E5%8F%A3.js
虽然不是一个类型的语言/环境(**无意比较长短**), 但有这样的例程至少能知道最后写出来的程序是怎么样的.
